version: '2'
services:
  pirri:
    build:
      context: .
    image: noaa/pirri:latest
    container_name: pirri
    restart: always
    ports:
      - "5006:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
