version: '2'
services:
  pirrid:
    build:
      context: .
    image: noaa/pirrid:latest
    container_name: pirrid
    restart: always
    ports:
      - "5007:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
