version: '2'
services:
  pirrip:
    ports:
      - "5016:80"
    logging:
      driver: "journald"
    volumes:
      - "pri_logs:/usr/src/PRI/logs"
    environment:
      TZ: "Pacific/Honolulu"
volumes:
  pri_logs:
