CREATE OR REPLACE SYNONYM DB_LOG_PKG FOR PRI.DB_LOG_PKG;
CREATE OR REPLACE SYNONYM PRI_PROJ_RES_TAG_MAX_SUM_ALL_V FOR PRI.PRI_PROJ_RES_TAG_MAX_SUM_ALL_V;
CREATE OR REPLACE SYNONYM PRI_RES_PROJ_TAG_MAX_SUM_ALL_V FOR PRI.PRI_RES_PROJ_TAG_MAX_SUM_ALL_V;
CREATE OR REPLACE SYNONYM PRI_RES_TYPES FOR PRI.PRI_RES_TYPES;
CREATE OR REPLACE SYNONYM PRI_RES_SCOPES FOR PRI.PRI_RES_SCOPES;
CREATE OR REPLACE SYNONYM PRI_DATA_SOURCES FOR PRI.PRI_DATA_SOURCES;
CREATE OR REPLACE SYNONYM PRI_PROJ FOR PRI.PRI_PROJ;
CREATE OR REPLACE SYNONYM PRI_PROJ_V FOR PRI.PRI_PROJ_V;
