CREATE OR REPLACE SYNONYM PRI_PROJ FOR PRI.PRI_PROJ;
CREATE OR REPLACE SYNONYM PRI_VC_USERS FOR PRI.PRI_VC_USERS;

CREATE OR REPLACE SYNONYM PRI_PROJ_RES FOR PRI.PRI_PROJ_RES;
CREATE OR REPLACE SYNONYM PRI_PROJ_TAGS FOR PRI.PRI_PROJ_TAGS;
CREATE OR REPLACE SYNONYM PRI_RES_TYPES FOR PRI.PRI_RES_TYPES;
CREATE OR REPLACE SYNONYM PRI_RES_SCOPES FOR PRI.PRI_RES_SCOPES;
CREATE OR REPLACE SYNONYM PRI_DATA_SOURCES FOR PRI.PRI_DATA_SOURCES;

CREATE OR REPLACE SYNONYM DB_LOG_PKG FOR PRI.DB_LOG_PKG;
