DROP SYNONYM PRI_PROJ;
DROP SYNONYM PRI_VC_USERS;

DROP SYNONYM PRI_PROJ_RES;
DROP SYNONYM PRI_PROJ_TAGS;
DROP SYNONYM PRI_RES_TYPES;
DROP SYNONYM PRI_RES_SCOPES;
DROP SYNONYM PRI_DATA_SOURCES;

DROP SYNONYM DB_LOG_PKG;
