DROP SYNONYM DB_LOG_PKG;
DROP SYNONYM PRI_PROJ_RES_TAG_MAX_SUM_ALL_V;
DROP SYNONYM PRI_RES_PROJ_TAG_MAX_SUM_ALL_V;
DROP SYNONYM PRI_RES_TYPES;
DROP SYNONYM PRI_RES_SCOPES;
DROP SYNONYM PRI_DATA_SOURCES;
DROP SYNONYM PRI_PROJ;
DROP SYNONYM PRI_PROJ_V;
